version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/requirements/"
    target-branch: "dev"
    schedule:
      interval: "daily"