[tool.ruff]

# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
# https://beta.ruff.rs/docs/rules/
lint.select = ["A", "B", "C", "D", "E", "F", "DTZ", "RUF", "S", "COM", "C4", "DJ", "EM", "ISC", "ICN", "PIE", "RET", "SLF", "SIM", "TID", "PD", "NPY"]
lint.ignore = [
    "SLF001",       # Private member accessed
    "D100",         # Missing docstring in public module
    "D101",         # Missing docstring in public class
    "D102",         # Missing docstring in public method
    "D103",         # Missing docstring in public function
    "D105",         # Missing docstring in magic method
    "D106",         # Missing docstring in public nested class
    "D107",         # Missing docstring in __init__
    "A003",         # attribute is shadowing a Python builtin
    "D203",         # 1 blank line required before class docstring
    "D213",         # Multi-line docstring summary should start at the first line
    "C901",         # McCabe complexity is too high
    "RUF012",       # Mutable class attributes should be annotated with `typing.ClassVar`
    "RUF100",       # For transition with workflow
    ]

# Allow autofix for all enabled rules (when `--fix`) is provided
lint.fixable = ["A", "B", "C", "D", "E", "F", "DTZ", "RUF", "S", "COM", "C4", "DJ", "EM", "ISC", "ICN", "PIE", "RET", "SLF", "SIM", "TID", "PD", "NPY"]
lint.unfixable = []

# Exclude a variety of commonly ignored directories.
lint.exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    ".venv",
    "migrations",
]

lint.pydocstyle.convention ="google"
# Same as Black.
line-length = 150

# Allow unused variables when underscore-prefixed.
lint.dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.11.
target-version = "py311"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403", "D104"]

[tool.ruff.lint.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 60