site_name: Django Napse Documentation

repo_name: napse-invest/django-napse
repo_url: https://github.com/napse-invest/django-napse


docs_dir: "docs/"


markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.snippets:
  - pymdownx.magiclink:
  - attr_list:
  - md_in_html:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite:
  - pymdownx.superfences:
  - markdown.extensions.attr_list:
  - pymdownx.keys:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - codehilite:
      use_pygments: true
      noclasses: true
      pygments_style: tango


plugins:
  - search

theme:
  name: 'material'
  logo: 'assets/images/NapseInvestLogoSVG.svg'
  favicon: 'theme/assets/images/logo.ico'
  language: 'en'
  palette:
   primary: 'white'
  custom_dir: 'docs/theme'
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - content.code.annotate
    - toc.integrate
    - toc.follow
    - navigation.path
    - navigation.top
    - content.code.copy


nav:
  - Home: 
    - Overview: "index.md"
  - Contributing: "contributing.md"
  #   - Installation:
  #   - Tutorial:
  # - API: