site_name: Django Napse Documentation
# site_url: https://go.napse-invest.com/visit/
repo_name: napse-invest/django-napse
repo_url: https://github.com/napse-invest/django-napse
copyright: MIT Licence


docs_dir: "docs/"


extra_css:
  -  assets/stylesheets/extra.css
  -  assets/stylesheets/api.css


theme:
  name: 'material'
  custom_dir: theme
  favicon: 'theme/assets/napse_logo_white.svg'
  logo: 'theme/assets/napse_invest_logo_white.svg'
  language: 'en'
  palette:
    # Palette toggle for light mode
    - media: "prefers-color-scheme: light"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        # icon: material/toggle-switch
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "prefers-color-scheme: dark"
      scheme: slate
      primary: teal
      accent: blue grey
      toggle:
        # icon: material/toggle-switch-off-outline
        icon: material/toggle-switch
        name: Switch to light mode

  custom_dir: 'docs/theme'
  features:
    - navigation.tabs
    - navigation.tabs.stickyx
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.section
    - content.code.annotate
    # - toc.integrate
    - toc.follow
    - navigation.path
    - navigation.top
    - content.code.copy
    - search.suggest

plugins:
  - search
  - inline-svg
  - coverage:
      page_name: coverage  # default
      html_report_dir: htmlcov  # default
  - neoteroi.mkdocsoad:
      use_pymdownx: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]

markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.snippets:
  - pymdownx.magiclink:
  - attr_list:
  - md_in_html:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite:
  - pymdownx.superfences:
  - pymdownx.keys:
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - codehilite:
      use_pygments: true
      noclasses: true
      pygments_style: tango
  - pymdownx.details:
  - pymdownx.tabbed:
      alternate_style: true


extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/NapseInvest
      name: X
    - icon: fontawesome/brands/linkedin
      link: https://fr.linkedin.com/company/napse-investment
      name: Linkedin
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/47gKBreSXa
      name: Discord
    - icon: fontawesome/brands/github
      link: https://github.com/napse-invest/Napse
      name: Github

nav:
  - Home: 
    - Overview: "index.md"
  - How to guides:
    - "sources/guides/exchange.md"
    - "sources/guides/exchange_account.md"
    - "sources/guides/space.md"
    - "sources/guides/fleet.md"
  - Reference:
    - "sources/reference/space.md"
  - API: "api.md"
  - Development: 
    - Contributing: "contributing.md"
    - Security: "SECURITY.md"
    - Coverage: coverage.md