# Generated by Django 4.2.5 on 2023-10-02 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_napse_auth", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NapseAPIKey",
        ),
    ]
