# Generated by Django 4.2.5 on 2023-10-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_napse_auth", "0002_delete_napseapikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="keypermission",
            name="revoked",
            field=models.BooleanField(default=False),
        ),
    ]
