# Generated by Django 3.2.15 on 2023-07-07 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NapseAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('napse_API_key', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_napse_core.exchange')),
                ('napse_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_napse_core.napseaccount')),
            ],
        ),
        migrations.CreateModel(
            name='BinanceAccount',
            fields=[
                ('exchangeaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_napse_core.exchangeaccount')),
                ('public_key', models.CharField(max_length=200)),
                ('private_key', models.CharField(max_length=200)),
            ],
            options={
                'unique_together': {('public_key', 'private_key')},
            },
            bases=('django_napse_core.exchangeaccount',),
        ),
    ]
