# Generated by Django 4.1.7 on 2023-07-12 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("django_napse_core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cluster",
            name="config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clusters",
                to="django_napse_core.botconfig",
            ),
        ),
        migrations.AlterField(
            model_name="cluster",
            name="fleet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clusters",
                to="django_napse_core.fleet",
            ),
        ),
    ]
