# Generated by Django 4.1.7 on 2023-08-13 18:39

from django.db import migrations, models
import django.db.models.deletion
import django_napse.utils.findable_class


class Migration(migrations.Migration):

    dependencies = [
        ("django_napse_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plugin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=255)),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plugins",
                        to="django_napse_core.strategy",
                    ),
                ),
            ],
            bases=(models.Model, django_napse.utils.findable_class.FindableClass),
        ),
        migrations.CreateModel(
            name="MBPPlugin",
            fields=[
                (
                    "plugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="django_napse_core.plugin",
                    ),
                ),
            ],
            bases=("django_napse_core.plugin",),
        ),
    ]
