# Generated by Django 4.2.5 on 2023-10-03 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_napse_core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cluster",
            old_name="bot",
            new_name="template_bot",
        ),
    ]
