# Generated by Django 4.1.7 on 2023-08-02 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_napse_core", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="napsespace",
            unique_together={("name", "identifier"), ("name", "exchange_account")},
        ),
    ]
