# Generated by Django 4.1.7 on 2023-08-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_napse_core", "0002_alter_napsespace_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="napsespace",
            unique_together={("name", "exchange_account")},
        ),
        migrations.AlterField(
            model_name="napsespace",
            name="identifier",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
