# Generated by Django 4.1.7 on 2023-07-12 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("django_napse_core", "0002_alter_cluster_config_alter_cluster_fleet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fleet",
            name="exchange_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="django_napse_core.exchangeaccount",
            ),
        ),
    ]
