# Generated by Django 4.1.7 on 2023-07-12 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_napse_core", "0003_alter_fleet_exchange_account"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="botconfig",
            unique_together=set(),
        ),
    ]
