# Generated by Django 4.1.7 on 2023-07-12 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("django_napse_core", "0004_alter_botconfig_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botincluster",
            name="bot",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bot_in_cluster",
                to="django_napse_core.bot",
            ),
        ),
    ]
