# Generated by Django 4.1.7 on 2023-07-13 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("django_napse_core", "0005_alter_botincluster_bot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cluster",
            name="config",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clusters",
                to="django_napse_core.botconfig",
            ),
        ),
    ]
