# Generated by Django 4.2.7 on 2024-03-15 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("django_napse_core", "0010_rename_napsespace_space"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategy",
            name="architecture",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="strategy", to="django_napse_core.architecture"),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="config",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="strategy", to="django_napse_core.botconfig"),
        ),
    ]
