# Generated by Django 4.1.7 on 2023-08-07 11:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_napse_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotSim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "simulation_reference",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, null=True, unique=True
                    ),
                ),
                ("bot_type", models.CharField(default="Bot", max_length=255)),
                ("investment", models.FloatField(default=1000)),
                ("start_date", models.DateTimeField(null=True)),
                ("end_date", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "space",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_napse_core.napsespace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BotSimSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=100)),
                ("target_type", models.CharField(max_length=100)),
                (
                    "bot_sim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="django_napse_simulations.botsim",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BotSimQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "simulation_reference",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("investment", models.FloatField(default=1000)),
                ("start_date", models.DateTimeField(null=True)),
                ("end_date", models.DateTimeField(null=True)),
                ("canceled", models.BooleanField(default=False)),
                ("status", models.CharField(default="IDLE", max_length=12)),
                ("completion", models.FloatField(default=0.0)),
                ("eta", models.DurationField(blank=True, null=True)),
                ("error", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bot_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_napse_core.botconfig",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BotSimDataPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("price", models.FloatField()),
                ("value", models.FloatField()),
                ("base", models.FloatField()),
                ("quote", models.FloatField()),
                ("mbp", models.FloatField(null=True)),
                ("amount", models.FloatField(null=True)),
                ("action", models.CharField(max_length=4)),
                (
                    "bot_sim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_points",
                        to="django_napse_simulations.botsim",
                    ),
                ),
            ],
        ),
    ]
