# Generated by Django 4.1.7 on 2023-08-10 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("django_napse_simulations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulationQueueInvestedCurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                ("amount", models.FloatField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investments",
                        to="django_napse_simulations.simulationqueue",
                    ),
                ),
            ],
            options={
                "unique_together": {("owner", "ticker")},
            },
        ),
        migrations.CreateModel(
            name="SimulationInvestedCurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                ("amount", models.FloatField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investments",
                        to="django_napse_simulations.simulation",
                    ),
                ),
            ],
            options={
                "unique_together": {("owner", "ticker")},
            },
        ),
    ]
