# Generated by Django 4.1.7 on 2023-08-09 14:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("django_napse_core", "0001_initial"),
        ("django_napse_simulations", "0004_alter_dataset_controller"),
    ]

    operations = [
        migrations.CreateModel(
            name="Simulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "simulation_reference",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, null=True, unique=True
                    ),
                ),
                ("investment", models.FloatField(default=1000)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bot",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulation",
                        to="django_napse_core.bot",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_napse_core.napsespace",
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="BotSimQueue",
            new_name="SimulationQueue",
        ),
        migrations.RemoveField(
            model_name="botsimsetting",
            name="bot_sim",
        ),
        migrations.RenameModel(
            old_name="BotSimDataPoint",
            new_name="SimulationDataPoint",
        ),
        migrations.DeleteModel(
            name="BotSim",
        ),
        migrations.DeleteModel(
            name="BotSimSetting",
        ),
        migrations.AlterField(
            model_name="simulationdatapoint",
            name="bot_sim",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_points",
                to="django_napse_simulations.simulation",
            ),
        ),
    ]
