# Generated by Django 4.1.7 on 2023-08-09 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_napse_simulations",
            "0005_simulation_rename_botsimqueue_simulationqueue_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="simulationdatapoint",
            old_name="bot_sim",
            new_name="simulation",
        ),
        migrations.RemoveField(
            model_name="simulationdatapoint",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="simulationdatapoint",
            name="base",
        ),
        migrations.RemoveField(
            model_name="simulationdatapoint",
            name="mbp",
        ),
        migrations.RemoveField(
            model_name="simulationdatapoint",
            name="price",
        ),
        migrations.RemoveField(
            model_name="simulationdatapoint",
            name="quote",
        ),
        migrations.AlterField(
            model_name="simulationdatapoint",
            name="action",
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name="SimulationDataPointExtraInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64)),
                ("value", models.CharField(max_length=64)),
                ("target_type", models.CharField(max_length=64)),
                (
                    "data_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_info",
                        to="django_napse_simulations.simulationdatapoint",
                    ),
                ),
            ],
        ),
    ]
