name: mkdocs

on:
  push:
    branches:
      - main
      - feature/mkdocs

permissions:
  contents: write
  
jobs:
  api-schema:
    name: API schema
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha || github.ref }}

    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        architecture: "x64"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools
        pip-compile ./requirements/development.txt --output-file ./full-requirements.txt --resolver=backtracking
        pip install -r ./full-requirements.txt

    - name: Lint with ruff
      run: python tests/test_app/manage.py spectacular --file docs/schema.yml

  deploy:
    needs: api-schema
    name: Deploy documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: |
          pip install -r requirements/development.txt
          mkdocs gh-deploy --force
