name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  pull_request_job:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Template Workflow
        uses: actions/github-script@v4
        with:
          script: |
            const token = process.env.GITHUB_TOKEN;
            const octokit = new Octokit({ auth: token });
            await octokit.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
              owner: 'tomjeannesson',
              repo: 'template-workflow',
              workflow_id: 'template_workflow',
              ref: 'main',
              inputs: {
                MAIN_SECRET: process.env.MAIN_SECRET
              }
            });
