name: Pypi

on:
  push:
    branches: ["feature/ci"]

jobs:
  pypi-release:
    name: Pypi release
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/djang-napse
    permissions:
      id-token: write

    steps:

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build package
      run: |
        python setup.py sdist

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1