name: Pypi

on:
  push:
    branches: ["feature/ci"]

jobs:
  test:
    name: Pypi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: test
        run: |
          echo "test"