name: Pypi

on:
  push:
    branches: ["feature/ci"]

jobs:
  pypi-release:
    name: Pypi release
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/djang-napse
    permissions:
      id-token: write
    steps:
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1