name: Upload django-napse Package

on:
  push:
    branches: [ feature/ci ]

jobs:
  test:
    steps:
    - name: Get latest commit
      id: commit
      run: |
        echo "::set-output name=hash::$(git log -1 --pretty=format:"%H")"
        echo "${{ steps.commit.outputs.hash }}"