name: Upload django-napse Package

on:
  push:
    branches: [ "feature/ci" ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Get latest commit
      id: commit
      run: |
        echo: "test"