name: Pypi

on:
  push:
    branches: ["feature/ci"]

jobs:
  pypi-release:
    name: Pypi release
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Get latest commit
      id: commit
      run: |
        echo "::set-output name=hash::$(git log -1 --pretty=format:"%H")"
        echo "commit: "
        echo ${{ steps.commit.outputs.hash }}