name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          src: "."
          args: --config .github/pyproject.toml
      - name: Run a one-line script
        run: |
          "ls -l"
