name: Ruff

on: [push]

jobs:
  Ruff:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Linting code with ruff
        uses: chartboost/ruff-action@v1
        with:
          src: "."
          args: --config .github/pyproject.toml

      - name: Linting code with ruff
        run: |
          python -m pip install ruff
          ruff . --config .github/pyproject.toml
