name: mkdocs

on:
  push:

permissions:
  contents: write
  
jobs:
  api-schema:
    name: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha || github.ref }}

    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        architecture: "x64"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools
        pip-compile ./requirements/development.txt --output-file ./full-requirements.txt --resolver=backtracking
        pip install -r ./full-requirements.txt

    - name: Print end of work
      run: echo -e "DONE!"