name: Main Workflow

on:
  workflow_run:
    workflows: ["Trigger Workflow"]
    types:
      - completed

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Use Secret in Workflow
        run: echo "My secret value is ${{ inputs.MY_SECRET }}"
        env:
          MY_SECRET: ${{ inputs.MY_SECRET }}
