name: Trigger Workflow

on:
  workflow_run:
    workflows: ["Main Workflow"]
    types:
      - requested

jobs:
  trigger_main_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Main Workflow
        uses: actions/github-script@v4
        with:
          script: |
            const forkedRepo = context.payload.workflow_run.head_repository.full_name;
            const mainWorkflow = context.payload.workflow_run.workflow;

            if (context.payload.workflow_run.head_repository.fork) {
              console.log(`Running ${mainWorkflow} on forked repository ${forkedRepo}`);
              const token = process.env.GITHUB_TOKEN;
              const octokit = new Octokit({ auth: token });
              await octokit.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
                owner: 'tomjeannesson',
                repo: 'napse-invest/django-napse',
                workflow_id: context.payload.workflow_run.workflow_id,
                ref: 'main',
                inputs: {
                  MY_SECRET: process.env.MY_SECRET
                }
              });
            } else {
              console.log(`Skipping ${mainWorkflow} as it's not a forked repository`);
            }
